### ISSUE TITLE
consider using Term.d library

### ISSUE THREAD

**Issue by vietj** [jmesnil/snowcamp-telnet-server#1]
it provides a telnet server implementation (also SSH and Websocket) : https://github.com/termd/termd :-)

**Comment by vietj** [comment]
ah actually it is an example based, never mind :)

**Comment by vietj** [comment]
actually it could be, I thougth it was some XNIO implementation.

**Comment by jmesnil** [comment]
@vietj I need to add a README :)

The demo is really about writing an extension to WildFly. I want a simple service for that, so I wrote a dummy telnet server which uses an executor and a server socket.
The idea is to show how to leverage WildFly to provide resources to the telnet server and manage it.
I'll consider the telnet server like a blackbox in the demo anyway :)

**Comment by vietj** [comment]
yes got that afterward :-)
